export const actionType = {
	GET_ROLES: 'GET_ROLES',
	SET_ROLES: 'SET_ROLES',
	SET_ERROR: 'SET_ERROR',
	CREATE_PLAYER: 'CREATE_PLAYER',
	CREATE_GAME: 'CREATE_GAME',
	START_GAME: 'START_GAME',
    WINDOW_RESIZE: 'WINDOW_RESIZE',
    CHANGE_ACTION: 'CHANGE_ACTION',
    SAVE_ACTIONS: 'SAVE_ACTIONS',
    START_ACCUSATIONS: 'START_ACCUSATIONS',
    SAVE_ACCUSATIONS: 'SAVE_ACCUSATIONS',
    CHANGE_STATE: 'CHANGE_STATE',
    SET_GAMEID: 'SET_GAMEID',
    SET_NIGHT: 'SET_NIGHT'
};
