export const actionType = {
	GET_ROLES: 'GET_ROLES',
	SET_ROLES: 'SET_ROLES',

	SET_ERROR: 'SET_ERROR',
	
	CREATE_PLAYER: 'CREATE_PLAYER',
	EDIT_PLAYER: 'EDIT_PLAYER',
	UPDATE_PLAYER: 'UPDATE_PLAYER',
	
	CREATE_GAME: 'CREATE_GAME',
    
    WINDOW_RESIZE: 'WINDOW_RESIZE',
    
    START_GAME: 'START_GAME',
    CHANGE_ACTION: 'CHANGE_ACTION',
    SAVE_ACTIONS: 'SAVE_ACTIONS'
};